SELECT 
    "MatchHistory" as match_history,
    "League" as league,
    "Season" as season,
    "Year" as "year",
    "blueTeamTag" as blue_team_tag ,
    "bResult" as b_result,
    "rResult" as r_result,
    "redTeamTag" as red_team_tag,
    "gamelength" as game_length_min,
    "blueTop" as blue_top,
    "blueTopChamp" as blue_top_champ,
    "blueJungle" as blue_jungle,
    "blueJungleChamp" as blue_jungle_champ,
    "blueMiddle" as blue_middle,
    "blueMiddleChamp" as blue_middle_champ,
    "blueADC" as blue_adc,
    "blueADCChamp" as blue_adc_champ,
    "blueSupport" as blue_support,
    "blueSupportChamp" as blue_support_champ,
    "redTop" as red_top,
    "redTopChamp" as red_top_champ,
    "redJungle" as red_jungle,
    "redJungleChamp" as red_jungle_champ,
    "redMiddle" as red_middle,
    "redMiddleChamp" as red_middle_champ,
    "redADC" as red_adc,
    "redADCChamp" as red_adc_champ,
    "redSupportChamp" as red_support_champ,
    "redSupport" as red_support 
from {{source('raw','match_data')}}