CREATE SCHEMA IF NOT EXISTS raw;

DROP TABLE IF EXISTS raw.match_data CASCADE;
DROP TABLE IF EXISTS raw.champ CASCADE;
DROP TABLE IF EXISTS raw.death_data CASCADE;
DROP TABLE IF EXISTS raw.ban_data CASCADE;
DROP TABLE IF EXISTS raw.role CASCADE;
